In [37]:
import pandas as pd
import os
import datetime as dt
import numpy as np
import json

def mark_to_numeric(mark):
    if pd.isna(mark):
        return np.nan

    mark = str(mark).strip()

    if ":" in mark:
        try:
            parts = [float(part) for part in mark.split(":")]
        except ValueError:
            return np.nan

        if len(parts) == 2:
            minutes, seconds = parts
            return minutes * 60 + seconds

        if len(parts) == 3:
            hours, minutes, seconds = parts
            return hours * 3600 + minutes * 60 + seconds

        return np.nan

    try:
        return float(mark)
    except ValueError:
        return np.nan

In [38]:
df = pd.read_csv('data.csv', sep=";")

KeyboardInterrupt:

In [ ]:
df.head()

# PRE-PROCESS DATASET

In [ ]:
df.isna().sum()

In [ ]:
df.describe()

In [6]:
try:
    df["Date"] = df.apply(lambda row: dt.datetime.strptime(str(row["Date"]), "%Y-%m-%d"), axis=1)
except ValueError:
    print(f"Error: The date is not in the correct format.")

In [7]:
try:
    df["DOB"] = df.apply(lambda row: dt.datetime.strptime(str(row["DOB"]), "%Y-%m-%d") if pd.notna(row["DOB"]) else pd.NaT, axis=1)
except ValueError as e:
    print(f"Error: The date is not in the correct format.")
    print(e)

In [8]:
df["Age"] = df.apply(lambda row: (row["Date"] - row["DOB"]).days // 365 if pd.notna(row["DOB"]) else pd.NaT, axis=1)

In [ ]:
df[df['Age'] < 14]

virer les âges < 11

In [10]:
df["Age"] = df["Age"].apply(lambda row: row if pd.notna(row) and row >= 11 else None)

In [ ]:
df.head()

In [12]:
df.to_csv('final_data.csv', index=False)

## catégorisation cols

In [13]:
df["Event"].unique()

array(['One Mile', 'Shot Put', '2000 Metres Steeplechase', 'Discus Throw',
       '5000 Metres Race Walk', '5 Kilometres Race Walk', '10 Kilometres',
       '10000 Metres Race Walk', '20 Kilometres Race Walk',
       '15 Kilometres', '1500 Metres', '400 Metres Hurdles',
       '110 Metres Hurdles', '100 Metres', '600 Metres',
       '3000 Metres Steeplechase', 'Decathlon', '3000 Metres',
       'Two Miles', '10 Miles Road', '50 Kilometres Race Walk',
       'Pole Vault', 'Hammer Throw', '10000 Metres', '5 Kilometres',
       '20 Kilometres', '200 Metres', 'Triple Jump', '2000 Metres',
       '20000 Metres Race Walk', '5000 Metres', '1000 Metres',
       '400 Metres', '30 Kilometres Race Walk', '300 Metres', 'Marathon',
       '3000 Metres Race Walk', 'Javelin Throw', 'Half Marathon',
       'High Jump', '35 Kilometres Race Walk', '800 Metres',
       '10 Kilometres Race Walk', 'Long Jump', '100 Metres Hurdles',
       'Heptathlon'], dtype=object)

In [14]:
DIST_EVENTS = ["Shot Put", "Discus Throw", "Hammer Throw", "Javelin Throw", "Long Jump", "Triple Jump", "High Jump", "Pole Vault"]
TIME_EVENTS = ["One Mile", "2000 Metres Steeplechase", "5000 Metres Race Walk", "5 Kilometres Race Walk",
    "10 Kilometres", "10000 Metres Race Walk", "20 Kilometres Race Walk", "15 Kilometres", "1500 Metres",
    "400 Metres Hurdles", "110 Metres Hurdles", "100 Metres", "600 Metres", "3000 Metres Steeplechase",
    "3000 Metres", "Two Miles", "10 Miles Road", "50 Kilometres Race Walk", "10000 Metres", "5 Kilometres",
    "20 Kilometres", "200 Metres", "2000 Metres", "20000 Metres Race Walk", "5000 Metres", "1000 Metres",
    "400 Metres", "30 Kilometres Race Walk", "300 Metres", "Marathon", "3000 Metres Race Walk",
    "Half Marathon", "800 Metres", "10 Kilometres Race Walk", "100 Metres Hurdles", "35 Kilometres Race Walk",
    "Heptathlon", "Decathlon"]

# col pour checker si dist event ou pas

In [15]:
df["Dist_Event"] = df["Event"].apply(lambda x: 1 if x in DIST_EVENTS else 0)

In [16]:
df.head()

,Rank,Mark,Competitor,DOB,Nat,Pos,Venue,Date,Results Score,Mark [meters or seconds],Event,Wind,Sex,Age,Dist_Event
0,1,3:43.13,Hicham EL GUERROUJ,1974-09-14,MAR,1,"Stadio Olimpico, Roma (ITA)",1999-07-07,1292,223.1,One Mile,NaN,male,24.0,0
1,2,3:43.40,Noah NGENY,1978-11-02,KEN,2,"Stadio Olimpico, Roma (ITA)",1999-07-07,1288,223.4,One Mile,NaN,male,20.0,0
2,3,3:44.39,Noureddine MORCELI,1970-02-28,ALG,1,Rieti (ITA),1993-09-05,1275,224.3,One Mile,NaN,male,23.0,0
3,4,3:44.60,Hicham EL GUERROUJ,1974-09-14,MAR,1,Nice (FRA),1998-07-16,1272,224.6,One Mile,NaN,male,23.0,0
4,5,3:44.90,Hicham EL GUERROUJ,1974-09-14,MAR,1,Oslo (NOR),1997-07-04,1268,224.9,One Mile,NaN,male,22.0,0

In [17]:
df.drop(columns=["Mark", "Results Score"])

,Rank,Competitor,DOB,Nat,Pos,Venue,Date,Mark [meters or seconds],Event,Wind,Sex,Age,Dist_Event
0,1,Hicham EL GUERROUJ,1974-09-14,MAR,1,"Stadio Olimpico, Roma (ITA)",1999-07-07,223.1,One Mile,NaN,male,24.0,0
1,2,Noah NGENY,1978-11-02,KEN,2,"Stadio Olimpico, Roma (ITA)",1999-07-07,223.4,One Mile,NaN,male,20.0,0
2,3,Noureddine MORCELI,1970-02-28,ALG,1,Rieti (ITA),1993-09-05,224.3,One Mile,NaN,male,23.0,0
3,4,Hicham EL GUERROUJ,1974-09-14,MAR,1,Nice (FRA),1998-07-16,224.6,One Mile,NaN,male,23.0,0
4,5,Hicham EL GUERROUJ,1974-09-14,MAR,1,Oslo (NOR),1997-07-04,224.9,One Mile,NaN,male,22.0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
461517,2206,Claire BRYANT,2001-08-25,USA,3,"Percy Beard Track, Gainesville, FL (USA)",2023-04-14,6.7,Long Jump,1.8,female,21.0,1
461518,2206,Sumire HATA,1996-05-04,JPN,1,"Prefectural Shizuoka Stadium, Fukuroi (JPN)",2023-05-03,6.7,Long Jump,2.0,female,27.0,1
461519,2206,Fátima DIAME,1996-09-22,ESP,1,"Helmántico, Salamanca (ESP)",2023-06-03,6.7,Long Jump,-2.7,female,26.0,1
461520,2206,Diana LESTI,1998-03-30,HUN,1,"Lantos Mihály Sportközpont, Budapest (HUN)",2023-06-08,6.7,Long Jump,-0.3,female,25.0,1
461521,2206,Hilary KPATCHA,1998-05-05,FRA,1f1,"Stadion Śląski, Chorzów (POL)",2023-06-25,6.7,Long Jump,-0.7,female,25.0,1

In [18]:
df["Place"]   = df["Venue"].str.extract(r"^(.*?)\s*\([A-Z]{3}\)\s*$")
df["Country"] = df["Venue"].str.extract(r"\(([A-Z]{3})\)\s*$")
df = df.drop(columns=["Venue"])

In [19]:
df.head()

,Rank,Mark,Competitor,DOB,Nat,Pos,Date,Results Score,Mark [meters or seconds],Event,Wind,Sex,Age,Dist_Event,Place,Country
0,1,3:43.13,Hicham EL GUERROUJ,1974-09-14,MAR,1,1999-07-07,1292,223.1,One Mile,NaN,male,24.0,0,"Stadio Olimpico, Roma",ITA
1,2,3:43.40,Noah NGENY,1978-11-02,KEN,2,1999-07-07,1288,223.4,One Mile,NaN,male,20.0,0,"Stadio Olimpico, Roma",ITA
2,3,3:44.39,Noureddine MORCELI,1970-02-28,ALG,1,1993-09-05,1275,224.3,One Mile,NaN,male,23.0,0,Rieti,ITA
3,4,3:44.60,Hicham EL GUERROUJ,1974-09-14,MAR,1,1998-07-16,1272,224.6,One Mile,NaN,male,23.0,0,Nice,FRA
4,5,3:44.90,Hicham EL GUERROUJ,1974-09-14,MAR,1,1997-07-04,1268,224.9,One Mile,NaN,male,22.0,0,Oslo,NOR

In [20]:
df.to_csv('final_data.csv', index=False)

# GRAPHES

## Bar Graph : # athlètes / nat

In [21]:
nationality_counts = df.drop_duplicates(subset='Competitor')['Nat'].value_counts()
nat_counts_dict = nationality_counts.to_dict()

with open("visualizations_data/bar_graph_ath_nat/data.json", "w") as f:
    json.dump(nat_counts_dict, f)

archi pas lisible => 20 most rep countries
urss & russie on merge ?

In [22]:
nationality_counts_20 = nationality_counts.sort_values(ascending=False).head(20)
nat_counts_dict_20 = nationality_counts_20.to_dict()

with open("visualizations_data/bar_graph_ath_nat/data_20.json", "w") as f:
    json.dump(nat_counts_dict_20, f)

## Bar Graph : répartition âge h/f

In [23]:
age_counts = df.groupby(["Sex"])['Age'].value_counts().sort_index()
age_counts_m_dict = age_counts["male"].to_dict()
age_counts_f_dict = age_counts["female"].to_dict()

with open("visualizations_data/duel_years/data_m.json", "w") as f:
    json.dump(age_counts_m_dict, f)
    
with open("visualizations_data/duel_years/data_f.json", "w") as f:
    json.dump(age_counts_f_dict, f)

## Camembert : répartition h/f

In [24]:
gender_counts = df.drop_duplicates(subset='Competitor')['Sex'].value_counts()
gender_counts_dict = gender_counts.to_dict()

with open("visualizations_data/pie_chart_gen/data.json", "w") as f:
    json.dump(gender_counts_dict, f)

## Evolution world records around the world and across time

In [65]:
df_worldrecords = pd.read_csv('worldrecords.csv', sep=",")

In [66]:
df_worldrecords["Country"] = df_worldrecords["Venue"].str.extract(r"\(([A-Z]{3})\)\s*$")

In [67]:
df_worldrecords["Country"].unique()

array(['URS', 'GER', 'AUS', 'USA', 'GDR', 'ITA', 'KOR', 'JPN', 'ESP',
       'CHN', 'NOR', 'SWE', 'RUS', 'BEL', 'TUN', 'ROU', 'SUI', 'POR',
       'FRA', 'GBR', 'BRA', 'POL', 'CZE', 'MON', 'NED', 'CRO'],
      dtype=object)

In [68]:
df_worldrecords["Sex"].unique()

array(['male', 'female'], dtype=object)

In [69]:
df_worldrecords.isna().sum()

Rank                         0
Mark                         0
Competitor                   0
DOB                          0
Nat                          0
Pos                          3
Venue                        0
Date                         0
Results Score                0
Mark [metres or seconds]     0
Event                        0
Wind                        77
Sex                          0
Country                      0
dtype: int64

### (1) Cumulative

In [98]:
df_wr = df_worldrecords.copy(deep=True)

In [99]:
import json
import pandas as pd
import pycountry

def get_country_name(country_code):
    if pd.isna(country_code):
        return None

    code = str(country_code).strip().upper()

    exceptions = {
        "URS": "RUS", "GDR": "DEU", "GER": "DEU", "ROC": "RUS",
        "NED": "NLD", "SUI": "CHE", "POR": "PRT", "MON": "MCO",
        "CRO": "HRV", "RSA": "ZAF", "NGR": "NGA",
    }

    if code in exceptions:
        return exceptions[code]

    country = pycountry.countries.get(alpha_3=code)
    if country:
        return country.alpha_3

    country = pycountry.countries.get(alpha_2=code)
    if country:
        return country.alpha_3

    return code


df_wr["Date"] = pd.to_datetime(df_wr["Date"], errors="coerce")
df_wr = df_wr.dropna(subset=["Date"]).copy()
df_wr["Year"] = df_wr["Date"].dt.year.astype(int)

df_wr["Sex"] = df_wr["Sex"].astype(str).str.strip().str.lower()
df_wr["Sex"] = df_wr["Sex"].map({"male": "M", "female": "F"})

df_wr["Country_of_Origin"] = df_wr["Nat"].apply(get_country_name)

df_cleaned = df_wr.dropna(subset=["Year", "Sex", "Country_of_Origin"]).copy()

print("Valeurs Sex uniques :", df_cleaned["Sex"].unique())
print("Nombre de lignes :", len(df_cleaned))
print("Années :", sorted(df_cleaned["Year"].unique())[:10], "...")

years = sorted(df_cleaned["Year"].unique())
sex = ["M", "F"]

final_json_structure = {}

for year in years:
    year_str = str(year)
    final_json_structure[year_str] = {"M": {}, "F": {}}

    for gender in sex:
        mask = (df_cleaned["Year"] <= year) & (df_cleaned["Sex"] == gender)
        data_until_now = df_cleaned[mask]

        if not data_until_now.empty:
            year_records_by_country = {}
            for country, group in data_until_now.groupby("Country_of_Origin"):
                year_records_by_country[country] = group[["Competitor", "Event"]].to_dict(orient="records")
            
            final_json_structure[year_str][gender] = year_records_by_country

print("Nb années dans JSON :", len(final_json_structure))
print("Première année :", next(iter(final_json_structure), None))

with open("visualizations_data/map_records/data_cumm.json", "w") as f:
    json.dump(final_json_structure, f, indent=2)

Valeurs Sex uniques : ['M' 'F']
Nombre de lignes : 87
Années : [np.int64(1980), np.int64(1983), np.int64(1985), np.int64(1986), np.int64(1987), np.int64(1988), np.int64(1990), np.int64(1991), np.int64(1993), np.int64(1994)] ...
Nb années dans JSON : 33
Première année : 1980

### (2) Not Cumulative

In [90]:
df_wr = df_worldrecords.copy(deep=True)

In [91]:
import json
import pandas as pd
import pycountry

def get_country_name(country_code):
    if pd.isna(country_code):
        return None

    code = str(country_code).strip().upper()

    exceptions = {
        "URS": "RUS", "GDR": "DEU", "GER": "DEU", "ROC": "RUS",
        "NED": "NLD", "SUI": "CHE", "POR": "PRT", "MON": "MCO",
        "CRO": "HRV", "RSA": "ZAF", "NGR": "NGA",
    }

    if code in exceptions:
        return exceptions[code]

    country = pycountry.countries.get(alpha_3=code)
    if country:
        return country.alpha_3

    country = pycountry.countries.get(alpha_2=code)
    if country:
        return country.alpha_3

    return code


df_wr["Date"] = pd.to_datetime(df_wr["Date"], errors="coerce")
df_wr = df_wr.dropna(subset=["Date"]).copy()
df_wr["Year"] = df_wr["Date"].dt.year.astype(int)

df_wr["Sex"] = df_wr["Sex"].astype(str).str.strip().str.lower()
df_wr["Sex"] = df_wr["Sex"].map({"male": "M", "female": "F"})

df_wr["Country_of_Origin"] = df_wr["Nat"].apply(get_country_name)

df_cleaned = df_wr.dropna(subset=["Year", "Sex", "Country_of_Origin"]).copy()

print("Valeurs Sex uniques :", df_cleaned["Sex"].unique())
print("Nombre de lignes :", len(df_cleaned))
print("Années :", sorted(df_cleaned["Year"].unique())[:10], "...")

years = sorted(df_cleaned["Year"].unique())
sexes = ["M", "F"]

final_json_structure = {}

for year in years:
    year_str = str(year)
    final_json_structure[year_str] = {"M": {}, "F": {}}

    for sex in ["M", "F"]:
        mask = (df_cleaned["Year"] == year) & (df_cleaned["Sex"] == sex)
        data_this_year = df_cleaned[mask]

        if not data_this_year.empty:
            year_records_by_country = {}
            
            for country, group in data_this_year.groupby("Country_of_Origin"):
                year_records_by_country[country] = group[["Competitor", "Event"]].to_dict(orient="records")
            
            final_json_structure[year_str][sex] = year_records_by_country

print("Nb années dans JSON :", len(final_json_structure))
print("Première année :", next(iter(final_json_structure), None))

with open("visualizations_data/map_records/data.json", "w") as f:
    json.dump(final_json_structure, f, indent=2)

Valeurs Sex uniques : ['M' 'F']
Nombre de lignes : 87
Années : [np.int64(1980), np.int64(1983), np.int64(1985), np.int64(1986), np.int64(1987), np.int64(1988), np.int64(1990), np.int64(1991), np.int64(1993), np.int64(1994)] ...
Nb années dans JSON : 33
Première année : 1980

## Overall world records championship

In [108]:
df_wr = df_worldrecords.copy(deep=True)

In [109]:
df_wr = df_wr.dropna(subset=["Sex", "Competitor"]).copy()
df_wr["Sex"] = df_wr["Sex"].astype(str).str.strip().str.lower().map({"male": "M", "female": "F"})

df_wr["Date"] = pd.to_datetime(df_wr["Date"], errors="coerce")
df_wr["Year"] = df_wr["Date"].dt.year.astype(int)

top_athletes_data = {"M": [], "F": []}

for gender in ["M", "F"]:
    gender_data = df_wr[df_wr["Sex"] == gender]
    
    top_names = gender_data["Competitor"].value_counts().head(3).index.tolist()
    
    for name in top_names:
        athlete_records = gender_data[gender_data["Competitor"] == name]
        details = athlete_records[["Year", "Event"]].sort_values("Year").to_dict(orient="records")
        
        top_athletes_data[gender].append({
            "Competitor": name,
            "Count": len(details),
            "Details": details
        })

output_path = f"visualizations_data/top_wr_holders/data.json"

with open(output_path, "w") as f:
    json.dump(top_athletes_data, f, indent=2)